<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CiudadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ciudades = [
            ['id_ciudad' => '050001', 'nombre_city' => 'MEDELLIN', 'id_departamento' => '05'],
            ['id_ciudad' => '050002', 'nombre_city' => 'ABEJORRAL', 'id_departamento' => '05'],
            ['id_ciudad' => '050004', 'nombre_city' => 'ABRIAQUI', 'id_departamento' => '05'],
            ['id_ciudad' => '050021', 'nombre_city' => 'ALEJANDRIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050030', 'nombre_city' => 'AMAGA', 'id_departamento' => '05'],
            ['id_ciudad' => '050031', 'nombre_city' => 'AMALFI', 'id_departamento' => '05'],
            ['id_ciudad' => '050034', 'nombre_city' => 'ANDES', 'id_departamento' => '05'],
            ['id_ciudad' => '050036', 'nombre_city' => 'ANGELOPOLIS', 'id_departamento' => '05'],
            ['id_ciudad' => '050038', 'nombre_city' => 'ANGOSTURA', 'id_departamento' => '05'],
            ['id_ciudad' => '050040', 'nombre_city' => 'ANORI', 'id_departamento' => '05'],
            ['id_ciudad' => '050042', 'nombre_city' => 'SANTAFE DE ANTIOQUIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050044', 'nombre_city' => 'ANZA', 'id_departamento' => '05'],
            ['id_ciudad' => '050045', 'nombre_city' => 'APARTADO', 'id_departamento' => '05'],
            ['id_ciudad' => '050051', 'nombre_city' => 'ARBOLETES', 'id_departamento' => '05'],
            ['id_ciudad' => '050055', 'nombre_city' => 'ARGELIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050059', 'nombre_city' => 'ARMENIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050079', 'nombre_city' => 'BARBOSA', 'id_departamento' => '05'],
            ['id_ciudad' => '050086', 'nombre_city' => 'BELMIRA', 'id_departamento' => '05'],
            ['id_ciudad' => '050088', 'nombre_city' => 'BELLO', 'id_departamento' => '05'],
            ['id_ciudad' => '050091', 'nombre_city' => 'BETANIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050093', 'nombre_city' => 'BETULIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050101', 'nombre_city' => 'CIUDAD BOLIVAR', 'id_departamento' => '05'],
            ['id_ciudad' => '050107', 'nombre_city' => 'BRICEÑO', 'id_departamento' => '05'],
            ['id_ciudad' => '050113', 'nombre_city' => 'BURITICA', 'id_departamento' => '05'],
            ['id_ciudad' => '050120', 'nombre_city' => 'CACERES', 'id_departamento' => '05'],
            ['id_ciudad' => '050125', 'nombre_city' => 'CAICEDO', 'id_departamento' => '05'],
            ['id_ciudad' => '050129', 'nombre_city' => 'CALDAS', 'id_departamento' => '05'],
            ['id_ciudad' => '050134', 'nombre_city' => 'CAMPAMENTO', 'id_departamento' => '05'],
            ['id_ciudad' => '050138', 'nombre_city' => 'CAÑASGORDAS', 'id_departamento' => '05'],
            ['id_ciudad' => '050142', 'nombre_city' => 'CARACOLI', 'id_departamento' => '05'],
            ['id_ciudad' => '050145', 'nombre_city' => 'CARAMANTA', 'id_departamento' => '05'],
            ['id_ciudad' => '050147', 'nombre_city' => 'CAREPA', 'id_departamento' => '05'],
            ['id_ciudad' => '050148', 'nombre_city' => 'EL CARMEN DE VIBORAL', 'id_departamento' => '05'],
            ['id_ciudad' => '050150', 'nombre_city' => 'CAROLINA', 'id_departamento' => '05'],
            ['id_ciudad' => '050154', 'nombre_city' => 'CAUCASIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050172', 'nombre_city' => 'CHIGORODO', 'id_departamento' => '05'],
            ['id_ciudad' => '050190', 'nombre_city' => 'CISNEROS', 'id_departamento' => '05'],
            ['id_ciudad' => '050197', 'nombre_city' => 'COCORNA', 'id_departamento' => '05'],
            ['id_ciudad' => '050206', 'nombre_city' => 'CONCEPCION', 'id_departamento' => '05'],
            ['id_ciudad' => '050209', 'nombre_city' => 'CONCORDIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050212', 'nombre_city' => 'COPACABANA', 'id_departamento' => '05'],
            ['id_ciudad' => '050234', 'nombre_city' => 'DABEIBA', 'id_departamento' => '05'],
            ['id_ciudad' => '050237', 'nombre_city' => 'DON MATIAS', 'id_departamento' => '05'],
            ['id_ciudad' => '050240', 'nombre_city' => 'EBEJICO', 'id_departamento' => '05'],
            ['id_ciudad' => '050250', 'nombre_city' => 'EL BAGRE', 'id_departamento' => '05'],
            ['id_ciudad' => '050264', 'nombre_city' => 'ENTRERRIOS', 'id_departamento' => '05'],
            ['id_ciudad' => '050266', 'nombre_city' => 'ENVIGADO', 'id_departamento' => '05'],
            ['id_ciudad' => '050282', 'nombre_city' => 'FREDONIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050284', 'nombre_city' => 'FRONTINO', 'id_departamento' => '05'],
            ['id_ciudad' => '050306', 'nombre_city' => 'GIRALDO', 'id_departamento' => '05'],
            ['id_ciudad' => '050308', 'nombre_city' => 'GIRARDOTA', 'id_departamento' => '05'],
            ['id_ciudad' => '050310', 'nombre_city' => 'GOMEZ PLATA', 'id_departamento' => '05'],
            ['id_ciudad' => '050313', 'nombre_city' => 'GRANADA', 'id_departamento' => '05'],
            ['id_ciudad' => '050315', 'nombre_city' => 'GUADALUPE', 'id_departamento' => '05'],
            ['id_ciudad' => '050318', 'nombre_city' => 'GUARNE', 'id_departamento' => '05'],
            ['id_ciudad' => '050321', 'nombre_city' => 'GUATAPE', 'id_departamento' => '05'],
            ['id_ciudad' => '050347', 'nombre_city' => 'HELICONIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050353', 'nombre_city' => 'HISPANIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050360', 'nombre_city' => 'ITAGUI', 'id_departamento' => '05'],
            ['id_ciudad' => '050361', 'nombre_city' => 'ITUANGO', 'id_departamento' => '05'],
            ['id_ciudad' => '050364', 'nombre_city' => 'JARDIN', 'id_departamento' => '05'],
            ['id_ciudad' => '050368', 'nombre_city' => 'JERICO', 'id_departamento' => '05'],
            ['id_ciudad' => '050376', 'nombre_city' => 'LA CEJA', 'id_departamento' => '05'],
            ['id_ciudad' => '050380', 'nombre_city' => 'LA ESTRELLA', 'id_departamento' => '05'],
            ['id_ciudad' => '050390', 'nombre_city' => 'LA PINTADA', 'id_departamento' => '05'],
            ['id_ciudad' => '050400', 'nombre_city' => 'LA UNION', 'id_departamento' => '05'],
            ['id_ciudad' => '050411', 'nombre_city' => 'LIBORINA', 'id_departamento' => '05'],
            ['id_ciudad' => '050425', 'nombre_city' => 'MACEO', 'id_departamento' => '05'],
            ['id_ciudad' => '050440', 'nombre_city' => 'MARINILLA', 'id_departamento' => '05'],
            ['id_ciudad' => '050467', 'nombre_city' => 'MONTEBELLO', 'id_departamento' => '05'],
            ['id_ciudad' => '050475', 'nombre_city' => 'MURINDO', 'id_departamento' => '05'],
            ['id_ciudad' => '050480', 'nombre_city' => 'MUTATA', 'id_departamento' => '05'],
            ['id_ciudad' => '050483', 'nombre_city' => 'NARIÑO', 'id_departamento' => '05'],
            ['id_ciudad' => '050490', 'nombre_city' => 'NECOCLI', 'id_departamento' => '05'],
            ['id_ciudad' => '050495', 'nombre_city' => 'NECHI', 'id_departamento' => '05'],
            ['id_ciudad' => '050501', 'nombre_city' => 'OLAYA', 'id_departamento' => '05'],
            ['id_ciudad' => '050541', 'nombre_city' => 'PEÐOL', 'id_departamento' => '05'],
            ['id_ciudad' => '050543', 'nombre_city' => 'PEQUE', 'id_departamento' => '05'],
            ['id_ciudad' => '050576', 'nombre_city' => 'PUEBLORRICO', 'id_departamento' => '05'],
            ['id_ciudad' => '050579', 'nombre_city' => 'PUERTO BERRIO', 'id_departamento' => '05'],
            ['id_ciudad' => '050585', 'nombre_city' => 'PUERTO NARE', 'id_departamento' => '05'],
            ['id_ciudad' => '050591', 'nombre_city' => 'PUERTO TRIUNFO', 'id_departamento' => '05'],
            ['id_ciudad' => '050604', 'nombre_city' => 'REMEDIOS', 'id_departamento' => '05'],
            ['id_ciudad' => '050607', 'nombre_city' => 'RETIRO', 'id_departamento' => '05'],
            ['id_ciudad' => '050615', 'nombre_city' => 'RIONEGRO', 'id_departamento' => '05'],
            ['id_ciudad' => '050628', 'nombre_city' => 'SABANALARGA', 'id_departamento' => '05'],
            ['id_ciudad' => '050631', 'nombre_city' => 'SABANETA', 'id_departamento' => '05'],
            ['id_ciudad' => '050642', 'nombre_city' => 'SALGAR', 'id_departamento' => '05'],
            ['id_ciudad' => '050647', 'nombre_city' => 'SAN ANDRES DE CUERQUIA', 'id_departamento' => '05'],
            ['id_ciudad' => '050649', 'nombre_city' => 'SAN CARLOS', 'id_departamento' => '05'],
            ['id_ciudad' => '050652', 'nombre_city' => 'SAN FRANCISCO', 'id_departamento' => '05'],
            ['id_ciudad' => '050656', 'nombre_city' => 'SAN JERONIMO', 'id_departamento' => '05'],
            ['id_ciudad' => '050658', 'nombre_city' => 'SAN JOSE DE LA MONTAÑA', 'id_departamento' => '05'],
            ['id_ciudad' => '050659', 'nombre_city' => 'SAN JUAN DE URABA', 'id_departamento' => '05'],
            ['id_ciudad' => '050660', 'nombre_city' => 'SAN LUIS', 'id_departamento' => '05'],
            ['id_ciudad' => '050664', 'nombre_city' => 'SAN PEDRO', 'id_departamento' => '05'],
            ['id_ciudad' => '050665', 'nombre_city' => 'SAN PEDRO DE URABA', 'id_departamento' => '05'],
            ['id_ciudad' => '050667', 'nombre_city' => 'SAN RAFAEL', 'id_departamento' => '05'],
            ['id_ciudad' => '050670', 'nombre_city' => 'SAN ROQUE', 'id_departamento' => '05'],
            ['id_ciudad' => '050674', 'nombre_city' => 'SAN VICENTE', 'id_departamento' => '05'],
            ['id_ciudad' => '050679', 'nombre_city' => 'SANTA BARBARA', 'id_departamento' => '05'],
            ['id_ciudad' => '050686', 'nombre_city' => 'SANTA ROSA DE OSOS', 'id_departamento' => '05'],
            /* ...más ciudades... */
        ];
        \Illuminate\Support\Facades\DB::table('ciudad')->insertOrIgnore($ciudades);
    }
}
